### ISSUE TITLE
[Bug]   Mod(a,b) causes a crash when the denominator (b) is zero

### ISSUE THREAD

**Issue by bengismo** [TheGameCreators/AGKTier2#12]
The Mod(a,b) function causes a crash when the denominator (b) is zero on windows. This should not cause a crash and should instead show an error string detailing the fault.

**Comment by KevinCrossDCL** [comment]
> I have also experienced this problem with the latest version of Studio on a Mac (2020.04.18). It took a while finding the cause as to why the app was crashing and closing completely without any error messages.

**Comment by jamerbi** [comment]
I don't see why that should be a bug, maybe it would be a Request to show the error message as it does when you divide by 0. Also, this kind of exception always crash the applications

**Comment by PaulSJ** [comment]
This has been fixed in version 2020.04.30

**Comment by KevinCrossDCL** [comment]
Is that Classic only? The latest Studio version I see on Products page is 2020.04.16 where it isn't fixed.

**Comment by bengismo** [comment]
This HASNT been fixed on classic 2020.04.30c

It still causes a crash

**Comment by PaulSJ** [comment]
My mistake, I added a check in the compiler without realising that mod is now an AGK command rather than a compiler operator. I'll get it fixed for the next version
